import Head from "next/head";
import { Fragment } from "react";
import MainHeader from "./main-header";

function Layout(props) {
  return (
    <Fragment>
      <Head>
        <title>Event Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeader />
      <main>{props.children}</main>
    </Fragment>
  );
}
export default Layout;
